# Generated by Django 5.2.1 on 2025-06-27 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_team_members"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="manager",
            field=models.ForeignKey(
                limit_choices_to={"role": "MANAGER"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_teams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
